projectPath: vlocity
queries:
  - AttributeCategory
  - ContextAction
  - ContextDimension
  - ContextScope
  - EntityFilter
  - ObjectClass
  - ObjectContextRule
  - ObjectLayout
  - Pricebook2
  - PriceList
  - PricingVariable
  - Product2
  - Promotion
  - Rule
  - TimePlan
  - TimePolicy
  - UIFacet
  - UISection
  - VlocityFunction
  - VlocityPicklist
  - Attachment
  - AttributeAssignmentRule
  - VlocityAttachment
  - VlocitySearchWidgetSetup
  - Catalog
  - PricingPlan
  - OfferMigrationPlan
  - CpqConfigurationSetup
  - InterfaceImplementation
  - StoryObjectConfiguration
  - String
  - VlocityDataPackType: SObject
    query: SELECT Id, Name FROM vlocity_cmt__IntegrationRetryPolicy__c
  - ContractType
  - Document
  - DocumentClause
  - VlocityStateModel
  - ItemImplementation
  - ManualQueue
  - OrchestrationDependencyDefinition
  - OrchestrationItemDefinition
  - OrchestrationPlanDefinition
  - System